# Generated by Django 4.0.6 on 2022-07-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_roll_updated_at_roll_randomdata_roll_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='modifier',
            field=models.IntegerField(default=0),
        ),
    ]
