# Generated by Django 4.0.6 on 2022-07-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_roll_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='description',
            field=models.CharField(default='', max_length=280),
            preserve_default=False,
        ),
    ]
