# Generated by Django 4.0.6 on 2022-07-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_roll_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='description',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
